config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "auth/github/callback", to: "sessions#create"
  delete :logout, to: "sessions#destroy"
  resources :redemptions, only: %i[create]
  get :redeem, to: "redemptions#new", as: :new_redemption
  resources :purchases, only: %i[home index create]

  root "purchases#home"

  mount Sidekiq::Web => "/sidekiq"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/llama_ranch.rb
class LlamaRanch < ApplicationRecord
  geocoded_by :address, lookup: lambda { |obj| obj.geocoder_lookup }
  reverse_geocoded_by :lat, :long
  after_validation :geocode

  def address
    [street, city, state, country].compact.join(", ")
  end

  def geocoder_lookup
    if country_code == "RU" || "TR"
      :yandex
    elsif country_code == "CN"
      :baidu
    else
      :google
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/redemption.rb
class Redemption < ApplicationRecord
  belongs_to :user
  validates :kisses_redeemed, presence: true
  validate :kiss_count_cannot_exceed_available_kisses, on: :create

  private

  def kiss_count_cannot_exceed_available_kisses
    return if kisses_redeemed.blank?
    return unless kiss_count_exceeds_available_kisses?
    errors.add :kiss_count, "cannot be more than the kisses you have purchased"
  end

  def kiss_count_exceeds_available_kisses?
    kisses_redeemed > available_kisses
  end

  def available_kisses
    user.remaining_kisses
  end
end

app/models/session.rb
class Session
  attr_reader :user, :oauth_payload

  def initialize(oauth_payload)
    @oauth_payload = oauth_payload
    @new_user = false

    find_or_create_user_from_oauth_payload
  end

  def new_user?
    @new_user
  end

  private

  def find_or_create_user_from_oauth_payload
    @user = existing_user_from_oauth || create_user_from_oauth
  end

  def existing_user_from_oauth
    User.find_by(oauth_id: oauth_payload.uid)
  end

  def create_user_from_oauth
    @new_user = true

    User.create!(
      oauth_id: oauth_payload.uid,
      oauth_token: oauth_payload.credentials.token,
      name: oauth_payload.info.name,
      email: oauth_payload.info.email,
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :purchases
  has_many :redemptions

  def remaining_kisses
    purchases.joins(:product).sum(:kiss_count) - redemptions.sum(:kisses_redeemed)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home; end

  private

  def sign_in_user(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def home
    @products = Product.order(:price)
  end

  def index
    @purchases = current_user.purchases.order(created_at: :desc).includes(:product)
  end

  def create
    token = params[:stripeToken]
    product = Product.find(params[:product_id])

    charge = Stripe::Charge.create(
      amount: product.price,
      currency: "usd",
      description: "#{product.name} - #{product.kiss_count} llama kisses",
      source: token,
    )

    current_user.purchases.create!(
      product: product,
      stripe_charge_id: charge.id,
    )

    PurchaseMailer.redemption_reminder_email(current_user.purchases.last).deliver_later(wait: 1.day)
  end

  private

  def total_kisses_purchased
    Purchase.joins(:product).sum(:kiss_count)
  end

  def total_kisses_redeemed
    Redemption.sum(:kisses_redeemed)
  end
end

app/controllers/redemptions_controller.rb
class RedemptionsController < ApplicationController
  def new
    @redemption = Redemption.new
    @nearest_llama_ranches = LlamaRanch.near(params[:search])
  end

  def create
    @redemption = current_user.redemptions.new(redemption_params)

    unless @redemption.save
      @nearest_llama_ranches = []
      render :new
    end
  end

  private

  def redemption_params
    params.require(:redemption).permit(:kisses_redeemed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    sign_in_user oauth_session.user
    if oauth_session.new_user?
      RemindUserToPurchaseWorker.perform_in(3.days, oauth_session.user.id)
    end
    redirect_to request.env["omniauth.origin"]
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def oauth_session
    @session ||= Session.new(request.env["omniauth.auth"])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_currency(price_in_cents)
    number_to_currency(price_in_cents / 100)
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/redemptions_helper.rb
module RedemptionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LlamaKisses</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1>Llama Kisses Megastore</h1>
      <% if current_user %>
        <div class="button-group">
          <%= link_to "Home", root_path, class: "button" %>
          <%= link_to "Redeem", new_redemption_path, class: "button" %>
          <%= link_to "Order History", purchases_path, class: "button" %>
          <%= link_to "Log out", logout_path, method: :delete, class: "button" %>
        </div>
      <% else %>
        <div class="button-group">
          <%= link_to "Log in with GitHub", "/auth/github", class: "button"%>
        </div>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/purchases/create.html.erb
<div class='thanks'>
<p>Thanks for buying!</p>
<p>You can redeem your llama kisses at your nearest llama ranch.</p>
<p><%= link_to "Buy more kisses!", root_path %></p>
</div>

app/views/purchases/home.html.erb
<% if current_user %>
  <p class='remaining-kisses'>You currently have <%= current_user.remaining_kisses %> kisses!</p>
  <div class='products-listing'>
    <% @products.each do |product| %>
      <%= form_tag purchases_path do %>
        <p class="product-name"><%= product.name %></p>
        <p class="product-description"><%= product.kiss_count %> kisses </p>
        <p class="product-price"><%= format_currency(product.price) %></p>
        <p><%= hidden_field_tag(:product_id, product.id) %></p>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>"
          data-amount="<%= product.price %>"
          data-name="Llama Kiss Megastore"
          data-description="<%= pluralize(product.kiss_count, "kisses") %>"
          data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
          data-locale="auto">
        </script>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/purchases/index.html.erb
<table>
  <thead>
    <tr>
      <th>Purchased at</th>
      <th>Product Name</th>
      <th>Number of Kisses</th>
    </tr>
  </thead>
  
  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= purchase.product.name %></td>
        <td><%= purchase.product.kiss_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/redemptions/create.html.erb
<div class='thanks'>
  <% @redemption.kisses_redeemed.times do %>
    💋
  <% end %>
<p>Thanks for redeeming!</p>
<p><%= link_to "Buy more kisses!", root_path %></p>
</div>

app/views/redemptions/new.html.erb
<% if @redemption.errors.any? %>
  <ul>
    <% @redemption.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div id="virtual-kisses">
  <p>You can virtually redeem kisses here! How many 💋 would you like?</p>
  <%= form_for @redemption do |f| %>
    <%= f.label :kisses_redeemed, label: false %>
    <%= f.text_field :kisses_redeemed %>
    <%= f.submit 'Redeem Kisses!', class: "button redeem-button"%>
  <% end %>
</div>

<div id="llama-ranch-lookup">
  <p>Or you can look up the closest llama ranches to you to plan a trip:</p>
  <%= form_tag(new_redemption_path, method: :get) do %>
    <%= label_tag :search %>
    <%= text_field_tag :search, params[:search] %>

    <%= submit_tag "Search", class: "button search-button"%>
  <% end %>
  <ul>
    <% @nearest_llama_ranches.each do |llama_ranch| %>
    <li><%= llama_ranch.address %></li>
    <% end %>
  </ul>
</div>